//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JAEscobarCandidatoEntities : DbContext
    {
        public JAEscobarCandidatoEntities()
            : base("name=JAEscobarCandidatoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoEstima> AutoEstimas { get; set; }
        public virtual DbSet<Estre> Estres { get; set; }
        public virtual DbSet<Personalidad> Personalidads { get; set; }
        public virtual DbSet<Sinceridad> Sinceridads { get; set; }
        public virtual DbSet<Candidato> Candidatoes { get; set; }
    
        public virtual int AddCandidato(string nombre, string apellidoPaterno, string apellidoMaterno, string email, string genero, Nullable<System.DateTime> fechaNacimiento, string telefono, Nullable<int> idSinceridad, Nullable<int> idAutoEstima, Nullable<int> idPersonalidad, Nullable<int> idEstres)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoPaternoParameter = apellidoPaterno != null ?
                new ObjectParameter("ApellidoPaterno", apellidoPaterno) :
                new ObjectParameter("ApellidoPaterno", typeof(string));
    
            var apellidoMaternoParameter = apellidoMaterno != null ?
                new ObjectParameter("ApellidoMaterno", apellidoMaterno) :
                new ObjectParameter("ApellidoMaterno", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var idSinceridadParameter = idSinceridad.HasValue ?
                new ObjectParameter("IdSinceridad", idSinceridad) :
                new ObjectParameter("IdSinceridad", typeof(int));
    
            var idAutoEstimaParameter = idAutoEstima.HasValue ?
                new ObjectParameter("IdAutoEstima", idAutoEstima) :
                new ObjectParameter("IdAutoEstima", typeof(int));
    
            var idPersonalidadParameter = idPersonalidad.HasValue ?
                new ObjectParameter("IdPersonalidad", idPersonalidad) :
                new ObjectParameter("IdPersonalidad", typeof(int));
    
            var idEstresParameter = idEstres.HasValue ?
                new ObjectParameter("IdEstres", idEstres) :
                new ObjectParameter("IdEstres", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddCandidato", nombreParameter, apellidoPaternoParameter, apellidoMaternoParameter, emailParameter, generoParameter, fechaNacimientoParameter, telefonoParameter, idSinceridadParameter, idAutoEstimaParameter, idPersonalidadParameter, idEstresParameter);
        }
    
        public virtual int DeleteCandidato(Nullable<int> idCandidato)
        {
            var idCandidatoParameter = idCandidato.HasValue ?
                new ObjectParameter("IdCandidato", idCandidato) :
                new ObjectParameter("IdCandidato", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCandidato", idCandidatoParameter);
        }
    
        public virtual ObjectResult<GetAllCandidato_Result> GetAllCandidato()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllCandidato_Result>("GetAllCandidato");
        }
    
        public virtual int UpdateCandidato(Nullable<int> idCandidato, string nombre, string apellidoPaterno, string apellidoMaterno, string email, string genero, Nullable<System.DateTime> fechaNacimiento, string telefono, Nullable<int> idSinceridad, Nullable<int> idAutoEstima, Nullable<int> idPersonalidad, Nullable<int> idEstres)
        {
            var idCandidatoParameter = idCandidato.HasValue ?
                new ObjectParameter("IdCandidato", idCandidato) :
                new ObjectParameter("IdCandidato", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoPaternoParameter = apellidoPaterno != null ?
                new ObjectParameter("ApellidoPaterno", apellidoPaterno) :
                new ObjectParameter("ApellidoPaterno", typeof(string));
    
            var apellidoMaternoParameter = apellidoMaterno != null ?
                new ObjectParameter("ApellidoMaterno", apellidoMaterno) :
                new ObjectParameter("ApellidoMaterno", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var idSinceridadParameter = idSinceridad.HasValue ?
                new ObjectParameter("IdSinceridad", idSinceridad) :
                new ObjectParameter("IdSinceridad", typeof(int));
    
            var idAutoEstimaParameter = idAutoEstima.HasValue ?
                new ObjectParameter("IdAutoEstima", idAutoEstima) :
                new ObjectParameter("IdAutoEstima", typeof(int));
    
            var idPersonalidadParameter = idPersonalidad.HasValue ?
                new ObjectParameter("IdPersonalidad", idPersonalidad) :
                new ObjectParameter("IdPersonalidad", typeof(int));
    
            var idEstresParameter = idEstres.HasValue ?
                new ObjectParameter("IdEstres", idEstres) :
                new ObjectParameter("IdEstres", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCandidato", idCandidatoParameter, nombreParameter, apellidoPaternoParameter, apellidoMaternoParameter, emailParameter, generoParameter, fechaNacimientoParameter, telefonoParameter, idSinceridadParameter, idAutoEstimaParameter, idPersonalidadParameter, idEstresParameter);
        }
    
        public virtual ObjectResult<GetByIdCandidato_Result> GetByIdCandidato(Nullable<int> idCandidato)
        {
            var idCandidatoParameter = idCandidato.HasValue ?
                new ObjectParameter("IdCandidato", idCandidato) :
                new ObjectParameter("IdCandidato", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetByIdCandidato_Result>("GetByIdCandidato", idCandidatoParameter);
        }
    
        public virtual ObjectResult<GetAllEmpresa_Result> GetAllEmpresa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllEmpresa_Result>("GetAllEmpresa");
        }
    
        public virtual ObjectResult<EmpresaGetByIdVacante_Result> EmpresaGetByIdVacante(Nullable<int> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmpresaGetByIdVacante_Result>("EmpresaGetByIdVacante", idEmpresaParameter);
        }
    
        public virtual ObjectResult<GetAllVacante_Result> GetAllVacante()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllVacante_Result>("GetAllVacante");
        }
    
        public virtual ObjectResult<VacanteGetByIdCandidato_Result> VacanteGetByIdCandidato(Nullable<int> idVacante)
        {
            var idVacanteParameter = idVacante.HasValue ?
                new ObjectParameter("IdVacante", idVacante) :
                new ObjectParameter("IdVacante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VacanteGetByIdCandidato_Result>("VacanteGetByIdCandidato", idVacanteParameter);
        }
    
        public virtual ObjectResult<VacanteStatusGetByIdCandidato_Result> VacanteStatusGetByIdCandidato(Nullable<int> idVacante, Nullable<int> idStatusPostulacion)
        {
            var idVacanteParameter = idVacante.HasValue ?
                new ObjectParameter("IdVacante", idVacante) :
                new ObjectParameter("IdVacante", typeof(int));
    
            var idStatusPostulacionParameter = idStatusPostulacion.HasValue ?
                new ObjectParameter("IdStatusPostulacion", idStatusPostulacion) :
                new ObjectParameter("IdStatusPostulacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VacanteStatusGetByIdCandidato_Result>("VacanteStatusGetByIdCandidato", idVacanteParameter, idStatusPostulacionParameter);
        }
    
        public virtual ObjectResult<StatusPostulacionGetById_Result> StatusPostulacionGetById(Nullable<int> idStatusPostulacion)
        {
            var idStatusPostulacionParameter = idStatusPostulacion.HasValue ?
                new ObjectParameter("IdStatusPostulacion", idStatusPostulacion) :
                new ObjectParameter("IdStatusPostulacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StatusPostulacionGetById_Result>("StatusPostulacionGetById", idStatusPostulacionParameter);
        }
    
        public virtual ObjectResult<Procesados_Result> Procesados(Nullable<int> idVacante)
        {
            var idVacanteParameter = idVacante.HasValue ?
                new ObjectParameter("IdVacante", idVacante) :
                new ObjectParameter("IdVacante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Procesados_Result>("Procesados", idVacanteParameter);
        }
    
        public virtual ObjectResult<ProcesadoCandidato_Result> ProcesadoCandidato(Nullable<int> idCandidato)
        {
            var idCandidatoParameter = idCandidato.HasValue ?
                new ObjectParameter("IdCandidato", idCandidato) :
                new ObjectParameter("IdCandidato", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcesadoCandidato_Result>("ProcesadoCandidato", idCandidatoParameter);
        }
    }
}
